version: "3.8"

services:
  db:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports: 
      - "5432:5432"
  web:
    build: .
    command:  sh -c 'python manage.py migrate --no-input && python manage.py runserver 0.0.0.0:8000'
    volumes: 
       - .:/code
    depends_on:
      - db
    ports:
      - "8000:8000"
      