name: example docker CI

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]

jobs:
  build:
    
    runs-on: [ubuntu-18.04] #OS ubuntu
    strategy:
      matrix:
        python-version: [3.8]
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
      
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.ACCESS_TOKEN }}


