name: example docker CI

on:
  push:
    branches: [master]


jobs:
  build:
    
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.ACCESS_TOKEN }}


